name: Build and Package Artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

env:
  OUT_DIR: hallowdale-v${{ github.event.inputs.version }}
  TARBALL: hallowdale-v${{ github.event.inputs.version }}.tar.gz

jobs:
  build-artifacts:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
          - windows
        ocaml-compiler:
          - 4.13.1

    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: apt-get update
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get update

      - name: set up ocaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: set up opam
        run: |
          opam pin -n .
          opam install . --deps-only
          opam exec -- dune build --profile release

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ env.OUT_DIR }}
          path: _build/default/bin/main.exe

  package-artifacts:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: move artifacts into dist/
        run: |
          mv artifacts/windows-$OUT_DIR/main.exe dist/windows.exe
          mv artifacts/ubuntu-$OUT_DIR/main.exe dist/linux
          mv artifacts/macos-$OUT_DIR/main.exe dist/macos
          rm -rf artifacts
          sudo chmod a+x dist/linux dist/macos

      - name: tar
        run: |
          mkdir $OUT_DIR
          tar -czvf $TARBALL --exclude="assets/tiled/hk-reference/*" ./assets/ ./config/ ./dist/ ./saves/ LICENSE.md README.md CHANGELOG.md --no-recursion ./saves/
          mv $TARBALL $OUT_DIR

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARBALL }}
          path: ${{ env.OUT_DIR }}/${{ env.TARBALL }}
