name: Build and Package Artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

env:
  OUT_FILE: hallowdale-v${{ github.event.inputs.version }}.zip

jobs:
  build-artifacts:
    strategy:
      fail-fast: false
      matrix:
        os:
          #- macos
          - ubuntu
          #- windows
        ocaml-compiler:
          - 4.13.1

    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: apt-get update
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update

      - name: set up ocaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: set up opam
        run: |
          opam pin -n .
          opam install . --deps-only
          opam exec -- dune build --profile release

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hallowdale-${{ matrix.os }}-v${{ github.event.inputs.version }}
          path: _build/default/bin/main.exe

  package-artifacts:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: debug
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          ls -l artifacts/
          ls -l artifacts/hallowdale-ubuntu-*/*

      - name: move artifacts into dist/
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          # mv artifacts/hallowdale-windows-v$VERSION/main.exe dist/windows.exe
          mv artifacts/hallowdale-ubuntu-v$VERSION/main.exe dist/linux.exe
          # mv artifacts/hallowdale-macos-v$VERSION/main.exe dist/macos
          rm -rf artifacts
          # sudo chmod a+x artifacts/windows.exe artifacts/linux.exe artifacts/macos
          mkdir saves/

      - name: zip
        run: >
          zip -r $OUT_FILE . \
            --include "assets/*" "config/*" "dist/*" "saves/" \
            --exclude "assets/tiled/hk-reference/*"

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          # the "outer" here is because of the double zip file created when downloading artifacts
          name: outer-hallowdale-v${{ github.event.inputs.version }}
          path: ${{ env.OUT_FILE }}
